input {
  file {
    path => "/data/launches.ndjson"
    codec => "json"
    sincedb_path => "/dev/null"
    start_position => "beginning"
  }
}

filter {
  mutate {
    add_field => {
      "source" => "logstash"
      "ingested_at" => "%{@timestamp}"
    }
    rename => { "date_utc" => "launch_date" }
  }
}

output {
  opensearch {
    hosts => ["http://opensearch-node1:9200"]
    index => "spacex-logstash"
    document_id => "%{[id]}"
  }
  stdout { codec => dots }
}
