input {
  file {
    path => "/data/launches.ndjson"
    codec => "json"
    sincedb_path => "/dev/null"
    start_position => "beginning"
  }
}

filter {
  mutate {
    add_field => {
      "source" => "logstash"
      "ingested_at" => "%{@timestamp}"
    }
    rename => { "date_utc" => "launch_date" }
  }
  if [success] == false {
    mutate {
      add_tag => ["failed_launch"]
    }
  }
}

output {
  if "failed_launch" in [tags] {
    opensearch {
      hosts => ["http://opensearch-node1:9200"]
      index => "spacex-failures"
      document_id => "%{[id]}"
    }
  } else {
    opensearch {
      hosts => ["http://opensearch-node1:9200"]
      index => "spacex-logstash"
      document_id => "%{[id]}"
    }
  }
  stdout { codec => dots }
}
